### ISSUE TITLE
Crashes with segmentation fault.

### ISSUE THREAD

**Issue by BjornVT** [callemein/ros_robot#4]
The program crashes after some time when running the program. The coords are also wrong. The x-coord is in meters while the y-coords is centimeters. The coords when the robot is looking right at the marker is right, but when the robot is looking at a slight angle the coords are wrong. Sometimes there are also Unexpected marker orientations as output. Also maybe don't print with cout but only use topics.

output:
marker (x, y) = (0, 80.4)
robot  (x, y, theta) = (0.350338, 80.2895, -2.82677)
[ INFO] [1458919211.001024347]: Received: id = 120	x = 0.004989	z = 0.367287	yaw = -0.318612

**Comment by sam-melsen** [comment]
I've changed to program so all measurements are now in centimeters.

How does this program crash with a segmentation fault? I've run it like 20 minutes and everything is OK. Also, if you get an unexpected marker orientation, you probably used a marker id outside the valid range of 100-129 (which are the markers used on the board at De Nayer).

Please clarify the incorrect output with an example. Since I haven't tested this program with the robot, I don't know exactly how everything behaves.

**Comment by BjornVT** [comment]
We got the segmentation fault after about 5 min running the program and moving the robot. We used the board at De Nayer so every marker is in that range.

**Comment by sam-melsen** [comment]
Issue is fixed. The segmentation fault was due to a null pointer exception.
